""" bou.constants """

ASTERISK = '*'
BACK_SLASH = '\\'
BLANK = ''
DOUBLE_QUOTE = '"'
DOT_PY = '.py'
DOWNGRADE = 'downgrade'
FORWARD_SLASH = '/'
GT = '>'
INPUT = 'input'
LOCALTIME = 'localtime'
LT = '<'
MIGRATIONS_DEFAULT = 'migrations/'
NAME = 'name'
OUTPUT = 'output'
PIPE = '|'
QUESTION_MARK = '?'
QUOTE = '\''
SPACE = ' '
TYPE = 'type'
UNDERSCORE = '_'
UPGRADE = 'upgrade'
VERSION = 'version'
VERSION_CONST = 'VERSION'
