""" bou.constants """

ASTERISK = '*'
BACK_SLASH = '\\'
BLANK = ''
DOUBLE_QUOTE = '"'
DOT_PY = '.py'
FORWARD_SLASH = '/'
GT = '>'
LOCALTIME = 'localtime'
LT = '<'
MIGRATIONS_DEFAULT = 'migrations/'
NAME = 'name'
PIPE = '|'
QUESTION_MARK = '?'
QUOTE = '\''
SPACE = ' '
UNDERSCORE = '_'
VERSION = 'version'
