""" bou.types
    ~~~
    Custom types used throughout the application.

[1]: https://stackoverflow.com/questions/29850801/subclass-pathlib-path-fails
"""

import collections
from collections.abc import Iterable
import types
import typing
import pathlib

import bou.constants as const

"""
Brief describes a brief human readable string, typically from *args
"""
Brief = typing.NewType('Brief', list[str])


class _BouPath(type(pathlib.Path())):
    """ Thanks [1] """
    pass


class Database(_BouPath):
    """ typed pathlike for a sqlite database. """
    pass


class BouDir(_BouPath):
    """ typed pathlike for the BouDir. """
    pass


class BouFile(_BouPath):
    """ typed pathlike for the BouFile, should be inside a BouDir. """
    pass


class Migration(types.ModuleType):
    """ A module generated by bou with standard attributes and methods. """
    pass


""" Route()s are iterated to perform migrations. """
Route = typing.NewType('Route', Iterable[Migration])


"""
TemplateVars
    .localtime: when the template was generated.
    .name: provided by the end user.
    .uuid: that bundles all templates together.
    .version: issued to the migration.
"""
TemplateVars = collections.namedtuple('TemplateVars', [
    const.LOCALTIME,
    const.NAME,
    const.UUID,
    const.VERSION
])
