""" bou.lib.constants """

ASTERISK = '*'
BACK_SLASH = '\\'
BLANK = ''
DEFAULT_MIGRATIONS_DIRECTORY = 'migrations'
DOUBLE_QUOTE = '"'
DOT_PY = '.py'
FORWARD_SLASH = '/'
GT = '>'
INPUT = 'input'
LOCALTIME = 'localtime'
LT = '<'
NAME = 'name'
OUTPUT = 'output'
PIPE = '|'
QUESTION_MARK = '?'
QUOTE = '\''
SPACE = ' '
TYPE = 'type'
UNDERSCORE = '_'
VERSION = 'version'
VERSION_CONST = 'VERSION'
